defaults: &defaults
  github:
    callback_url: http://localhost:3000/oauth/callback?provider=github

development:
  <<: *defaults

test:
  <<: *defaults


production:
  github:
    callback_url: https://commitboards.herokuapp.com/oauth/callback?provider=github
