development:
  github:
    callback_url: http://localhost:3000/oauth/callback?provider=github

production:
  github:
    callback_url: https://commitboards.herokuapp.com/oauth/callback?provider=github
